
title:AKHIL JP # your name (or website title) here
logo: "/profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 Full Stack Developer(MEAN)
  <br><br>
  <a href="mailto:akhilakku008@gmail.com">akhilakku008@gmail.com</a>
  <br>
  <a href="https://www.linkedin.com/in/akhiljptvm">LinkedIn Profile</a>
  <br>
  <a href="https://www.gihub.com/akhiljptvm">Gihub</a> 
theme: jekyll-theme-minimal
