
# title:AKHIL JP # your name (or website title) here
# logo: "/profile.png?raw=true" # your photo (or logo) here
# description: > # your text below (remove <br> elements if you don't need line breaks)
#  Full Stack Developer(MEAN)
#   <br><br>
#   <a href="mailto:akhilakku008@gmail.com">akhilakku008@gmail.com</a>
#   <br>
#   <a href="https://www.linkedin.com/in/akhiljptvm">LinkedIn Profile</a>
#   <br>
#   <a href="https://www.gihub.com/akhiljptvm">Gihub</a> 
# logo: "/mypictransparent-2.png?raw=true"


title: AKHIL JP # your name (or website title) here
logo: "https://media.licdn.com/dms/image/C4D03AQEIN3KHQP1xXA/profile-displayphoto-shrink_800_800/0/1654966871259?e=1685577600&v=beta&t=vxjR-7j4JhUZOjrotR-J4f-LbKnUvRhciEZZWsQ2bss" # your photo (or logo) here
# logo: <img src="/mypictransparent.png?raw=true" width="150px" height = "150px">
description: > # your text below (remove <br> elements if you don't need line breaks)
 Full Stack Developr(MEAN)
  <br><br>
  <a href="mailto:akhilakku008@gmail.com">akhilakku008@gmail.com </a>
  <br>
  <a href="https://www.linkedin.com/in/akhiljptvm/">LinkedIn Profile</a>
  <br>
  <a href="https://www.gihub.com/akhiljptvm/">Github</a> 
theme: jekyll-theme-minimal
